name: CI para C


on: 
  push: 

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar compilador GCC
      run: sudo apt update && sudo apt install build-essential -y

    - name: compilar o programa
      run: gcc GitHub.c -o programa

    - name: executar o programa
      run: ./programa

    - name: Executar tester automatizados
      run: |
        gcc -o Teste Teste.c
        ./Teste
